# From: https://github.com/shuhaoliu/docker-clion-dev/blob/master/docker-compose.yml

version: '3'

services:
  gdbserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: clion_dev
    security_opt:
      - seccomp:unconfined
    container_name: debug
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - .:/home/debugger/rbd_helib_with_remote_debugger/
#      - /home/rbd/workspace/rbd/rbd_helib_with_remote_debugger/plots:/home/rbd/workspace/rbd/rbd_helib_with_remote_debugger/plots
#    working_dir:  /home/debugger/rbd_helib_with_remote_debugger/
    hostname: debug
